variables:
  dummy: value

jobs:
- job: windows
  pool:
    vmImage: 'win1803'
  steps:
  - task: PowerShell@2
    displayName: Build nanoserver images
    inputs:
      targetType: inline
      workingDirectory: nanoserver
      script: |
        [System.Environment]::OSVersion.Version  
        docker version

        # On an online machine, download the zip file.
        Invoke-WebRequest -UseBasicParsing -OutFile docker-18.09.0.zip https://download.docker.com/components/engine/windows-server/18.09/docker-18.09.0.zip
        #Stop Docker service
        Stop-Service docker
            
        # Extract the archive.
        Expand-Archive docker-18.09.0.zip -DestinationPath $Env:ProgramFiles -Force

        # Clean up the zip file.
        Remove-Item -Force docker-18.09.0.zip

        # Install Docker. This requires rebooting.
        $null = Install-WindowsFeature containers

        # Add Docker to the path for the current session.
        $env:path += ";$env:ProgramFiles\docker"

        # Optionally, modify PATH to persist across sessions.
        $newPath = "$env:ProgramFiles\docker;" +
        [Environment]::GetEnvironmentVariable("PATH",
        [EnvironmentVariableTarget]::Machine)

        [Environment]::SetEnvironmentVariable("PATH", $newPath,
        [EnvironmentVariableTarget]::Machine)

        # Register the Docker daemon as a service.
        dockerd --register-service

        # Start the Docker service.
        Start-Service docker

        docker version
        
        docker build --isolation hyperv -t acanthamoeba/minecraft-server:nanoserver-1803 --build-arg POWERSHELL_BASETAG=nanoserver-1803 --target minecraft .
        docker build --isolation hyperv -t acanthamoeba/minecraft-server:nanoserver-1709 --build-arg POWERSHELL_BASETAG=nanoserver-1709 --target minecraft .
        docker build --isolation hyperv -t acanthamoeba/minecraft-server:nanoserver-sac2016 --build-arg VARIANT=sac2016 --target minecraft .