variables:
  imageName: acanthamoeba/minecraft-server
  dockerUrl: https://download.docker.com/components/engine/windows-server/18.09/docker-18.09.0.zip

jobs:
- job: windows
  pool:
    vmImage: 'win1803'
  steps:
  - task: PowerShell@2
    displayName: Update Docker
    inputs:
      targetType: inline
      script: |
        Invoke-WebRequest -UseBasicParsing -OutFile docker.zip $(dockerUrl)
        Stop-Service docker
        Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles -Force
        Start-Service docker
  - task: PowerShell@2
    displayName: Build nanoserver images
    inputs:
      targetType: inline
      workingDirectory: nanoserver
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      script: |
        docker build --isolation hyperv -t $(imageName):nanoserver-1803 --build-arg POWERSHELL_BASETAG=nanoserver-1803 --target minecraft .
        docker build --isolation hyperv -t $(imageName):nanoserver-1709 --build-arg POWERSHELL_BASETAG=nanoserver-1709 --target minecraft .
        docker build --isolation hyperv -t $(imageName):nanoserver-sac2016 --build-arg VARIANT=sac2016 --target minecraft .
        
        docker manifest create acanthamoeba/minecraft-server:nanoserver acanthamoeba/minecraft-server:nanoserver-1803 acanthamoeba/minecraft-server:nanoserver-1709 acanthamoeba/minecraft-server:nanoserver-sac2016
