variables:
  azureSubscription: 'TE Account - NoBun (6c1f4f3b-f65f-4667-8f9e-b9c48e09cd6b)'
  acr: nobun
  dockerUrl: https://download.docker.com/components/engine/windows-server/18.09/docker-18.09.0.zip

jobs:
- job: windows
  pool:
    vmImage: 'win1803'
  steps:
  - task: PowerShell@2
    displayName: Build nanoserver images
    inputs:
      targetType: inline
      workingDirectory: nanoserver
      script: |
        Invoke-WebRequest -UseBasicParsing -OutFile docker.zip $(dockerUrl)
        Stop-Service docker
        Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles -Force
        Start-Service docker
        
        docker build --isolation hyperv -t acanthamoeba/minecraft-server:nanoserver-1803 --build-arg POWERSHELL_BASETAG=nanoserver-1803 --target minecraft .
        docker build --isolation hyperv -t acanthamoeba/minecraft-server:nanoserver-1709 --build-arg POWERSHELL_BASETAG=nanoserver-1709 --target minecraft .
        #docker build --isolation hyperv -t acanthamoeba/minecraft-server:nanoserver-sac2016 --build-arg VARIANT=sac2016 --target minecraft .
- job: linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: AzureCLI@1
    displayName: Build nanoserver images via ACR
    inputs:
      azureSubscription: $(azureSubscription)
      workingDirectory: nanoserver
      scriptLocation: inlineScript
      inlineScript: |
        az acr build -r $(acr) --build-arg POWERSHELL_BASETAG=nanoserver-1803 --os Windows -t acanthamoeba/minecraft-server:nanoserver-1803 .
        az acr build -r $(acr) --build-arg POWERSHELL_BASETAG=nanoserver-1709 --os Windows -t acanthamoeba/minecraft-server:nanoserver-1709 .