variables:
  imageName: acanthamoeba/minecraft-server
  dockerUrl: https://download.docker.com/components/engine/windows-server/18.09/docker-18.09.0.zip

jobs:
- job: windows
  pool:
    vmImage: 'win1803'
  strategy:
    matrix:
      1803:
        imageTag: nanoserver-1803
        VARIANT: nanoserver
        POWERSHELL_BASETAG: nanoserver-1803
      1709:
        imageTag: nanoserver-1709
        VARIANT: nanoserver
        POWERSHELL_BASETAG: nanoserver-1709
      2016:
        imageTag: nanoserver-sac2016
        VARIANT: sac-2016
        POWERSHELL_BASETAG: nanoserver
  steps:
  - task: PowerShell@2
    displayName: Update Docker
    inputs:
      targetType: inline
      script: |
        Invoke-WebRequest -UseBasicParsing -OutFile docker.zip $(dockerUrl)
        Stop-Service docker
        Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles -Force
        Start-Service docker
  - task: PowerShell@2
    displayName: Build nanoserver images
    inputs:
      targetType: inline
      workingDirectory: nanoserver
      script: |
        docker build --isolation hyperv -t $(imageName):$(imageTag) --build-arg VARIANT=$(VARIANT) --build-arg POWERSHELL_BASETAG=$(POWERSHELL_BASETAG) --target minecraft .
