variables:
  azureSubscription: 'TE Account - NoBun (6c1f4f3b-f65f-4667-8f9e-b9c48e09cd6b)'
  acr: nobun
  imageName: $(acr).azurecr.io/acanthamoeba/minecraft-server
  dockerEEUrl: https://download.docker.com/components/engine/windows-server/18.09/docker-18.09.0.zip

jobs:
- job: windows
  pool:
    vmImage: 'win1803'
  steps:
  - task: PowerShell@2
    displayName: Update Docker
    inputs:
      targetType: inline
      script: |
        Invoke-WebRequest -UseBasicParsing -OutFile docker.zip $(dockerEEUrl)
        Stop-Service docker
        Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles -Force
        Start-Service docker
  - task: PowerShell@2
    displayName: Build nanoserver images
    inputs:
      targetType: inline
      workingDirectory: nanoserver
      script: |
        docker build --isolation hyperv -t $(imageName):nanoserver-1803 --build-arg POWERSHELL_BASETAG=nanoserver-1803 --target minecraft .
        docker build --isolation hyperv -t $(imageName):nanoserver-1709 --build-arg POWERSHELL_BASETAG=nanoserver-1709 --target minecraft .
        docker build --isolation hyperv -t $(imageName):nanoserver-sac2016 --build-arg VARIANT=sac2016 --target minecraft .
  - task: AzureCLI@1
    displayName: Push images to ACR
    inputs:
      azureSubscription: $(azureSubscription)
      scriptLocation: inlineScript
      inlineScript: |
        az acr login -n $(acr)
        docker push $(imageName):nanoserver-1803
        docker push $(imageName):nanoserver-1709
        docker push $(imageName):nanoserver-sac2016

        $Env:DOCKER_CLI_EXPERIMENTAL = "enabled"
        docker manifest create $(imageName):nanoserver $(imageName):nanoserver-1803 $(imageName):nanoserver-1709 $(imageName):nanoserver-sac2016
        docker push $(imageName):nanoserver