pool:
  vmImage: 'Ubuntu 16.04'

variables:
  azureSubscription: 'TE Account - NoBun (6c1f4f3b-f65f-4667-8f9e-b9c48e09cd6b)'
  acr: nobun

steps:
- task: AzureCLI@1
  displayName: Build nanoserver images
  inputs:
    azureSubscription: $(azureSubscription)
    scriptLocation: inlineScript
    inlineScript: |
      az acr build -r $(acr) --build-arg POWERSHELL_BASETAG=nanoserver-1803 --os Windows
      az acr build -r $(acr) --build-arg POWERSHELL_BASETAG=nanoserver-1709 --os Windows
      az acr build -r $(acr) --build-arg VARIANT=sac2016 --os Windows