variables:
  dummy: value

jobs:
- job: windows
  pool:
    vmImage: 'win1803'
  steps:
  - task: PowerShell@2
    displayName: Build nanoserver images
    inputs:
      targetType: inline
      workingDirectory: nanoserver
      script: |
        Install-Module DockerMsftProvider -Force
        Install-Package Docker -ProviderName DockerMsftProvider -Force
        docker version
        docker build -t acanthamoeba/minecraft-server:nanoserver-1803 --build-arg POWERSHELL_BASETAG=nanoserver-1803 --target minecraft .
        docker build -t acanthamoeba/minecraft-server:nanoserver-1709 --build-arg POWERSHELL_BASETAG=nanoserver-1709 --target minecraft .
        docker build -t acanthamoeba/minecraft-server:nanoserver-sac2016 --build-arg VARIANT=sac2016 --target minecraft .